# Generated by Django 5.1.3 on 2024-11-07 10:21

import datetime
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('birth_date'), '-', models.Value(datetime.datetime(2024, 11, 7, 10, 21, 37, 631020))), output_field=models.CharField(max_length=255)),
        ),
    ]
