# Generated by Django 5.1.3 on 2024-11-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_full_name_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
