# Generated by Django 5.1.3 on 2024-11-23 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_profile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blocked_users",
            field=models.ManyToManyField(
                blank=True, related_name="blocked_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
