# Generated by Django 5.1.3 on 2024-11-07 10:28

import datetime
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.Value(datetime.datetime(2024, 11, 7, 10, 28, 14, 336105)), '-', models.F('birth_date')), output_field=models.PositiveSmallIntegerField()),
        ),
    ]
