# Generated by Django 5.1.3 on 2024-11-09 08:33

import chatroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to=chatroom.models.chatroom_icon_path)),
                ('cover_photo', models.ImageField(upload_to=chatroom.models.chatroom_cover_photo_path)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Chatroom',
                'verbose_name_plural': 'Chatrooms',
                'ordering': ['-pk'],
            },
        ),
    ]
