# Generated by Django 5.1.3 on 2024-11-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_chatroommessages_chatroompoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroompoints',
            old_name='points',
            new_name='point',
        ),
        migrations.AddField(
            model_name='chatroompoints',
            name='earned_at',
            field=models.DateTimeField(auto_created=True, default='2024-11-10 17:44:58'),
            preserve_default=False,
        ),
    ]
