# Generated by Django 5.1.3 on 2024-11-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_rename_points_chatroompoints_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroompoints',
            name='earned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
