# Generated by Django 5.1.3 on 2024-11-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0004_alter_chatroompoints_earned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroompoints',
            name='point',
            field=models.IntegerField(default=1),
        ),
    ]
