# Generated by Django 5.1.3 on 2024-11-24 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0007_alter_chatroompoints_chatroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='leader',
            field=models.ManyToManyField(related_name='leaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='moderators',
            field=models.ManyToManyField(related_name='moderators', to=settings.AUTH_USER_MODEL),
        ),
    ]
