# Generated by Django 5.1.3 on 2024-11-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friend", "0002_friendrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2024-11-21 06:08"),
            preserve_default=False,
        ),
    ]
